name: masworld
version: '1.5.1-SNAPSHOT'
main: com.mas6y6.masworld.Masworld
api-version: '1.21'
description: Masworld SMP Custom Item Handler Plugin
dependencies:
  server:
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  masworld.fixitems:
    description: Allows the player to fix items with NBT
    default: op

  masworld.admin:
    description: Allows the player to use admin commands
    default: op
